refactor: Migrate to IntelliJ Platform Plugin
kcl-lang/intellij-kcl pull request #44
Opened 2024-10-11 05:37 UTC by RehanChalana

- use new IntellijPlatform syntax in build.gradle.kts
- bump to lsp4ij:0.6.0
- bump to gradleVersion 8.10.0

#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [x] N
- [ ] Y 

#### 2. What is the scope of this PR (e.g. component or file name):

build.gradle.kts
gradle.properties
gradle/libs.versions.toml

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [x] Contains syntax changes
- [x] Contains variable changes
- [x] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [x] Manual test (add detailed scripts or steps below)
- [ ] Other

I have tried migrating from gradle Intellij plugin (1.x) to newer IntelliJ platform Plugin. But as i am not good with gradle tasks, i hope someone can please look into that and help me point in the right direction.

We should also add gradle properties like sinceBuild and updateBuild i am not really sure about them.

I was also trying to add the new syntax for "runIdeForUiTest" task, but again i am not sure about that.

So yes this pr really needs a review from someone !.

Also can you please give it a "hacktoberfest-accepted" tag, it will help me complete the hacktober-fest challenge

2024-10-11 05:41 UTC, RehanChalana commented
@He1pa @Peefy can you please look into it.

2024-10-11 06:09 UTC, He1pa commented
Do you have any documentation about sinceBuild and updateBuild or where did you refer to this migration? Previously we had 
```
pluginSinceBuild = 221
 # pluginUntilBuild = 233.*
``` 
 in gradle.properties. It means supported build number ranges and IntelliJ Platform versions 
We set a minimum version but no maximum version to be compatible with subsequent new versions. 
I am not sure if this means the same property

2024-10-12 08:45 UTC, He1pa requested changes

2024-10-12 08:45 UTC, He1pa commented on build.gradle.kts
> +            untilBuild = providers.gradleProperty("pluginUntilBuild")
Do we need untilBuild?

2024-10-12 08:45 UTC, He1pa commented on README.md
> +![image](https://github.com/user-attachments/assets/b0e4af8b-f4dc-4e93-ac05-b94020ba43dc)
save as static image

2024-10-12 09:00 UTC, RehanChalana commented on build.gradle.kts
> +            untilBuild = providers.gradleProperty("pluginUntilBuild")
I have removed it

2024-10-12 09:00 UTC, RehanChalana commented on README.md
> +![image](https://github.com/user-attachments/assets/b0e4af8b-f4dc-4e93-ac05-b94020ba43dc)
done

2024-10-12 09:19 UTC, He1pa approved these changes
LGTM

2024-10-12 09:24 UTC, merged